name: Run tests

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8.2]
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: |
        pip3 install --upgrade pip
        pip3 install poetry
        poetry config virtualenvs.create false
        poetry check
        poetry install --no-interaction --no-ansi
    - name: Run tests
      run: |
        python3 -m pytest
